name: Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  phpunit:
    name: PHPUnit
    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      # Invoke Apache once as root to ensure that /var/run/apache2 gets created
      - name: Set up the Apache process
        if: runner.os == 'Linux'
        run: sudo apachectl -t -C 'ServerName example.com' -D DUMP_VHOSTS

      - name: Verify default Apache configuration
        run: apachectl -t -C "ServerName example.com"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-suggest --no-progress

      - name: Run test suite
        run: composer test:unit
